# Generated by Django 5.2.9 on 2025-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО нотариуса', max_length=100, verbose_name='ФИО нотариуса')),
                ('fed_number', models.IntegerField(blank=True, default='', help_text='Фед. номер', max_length=20, verbose_name='Фед. номер')),
                ('reg_number', models.CharField(blank=True, default='', help_text='Регистрационный номер', max_length=20, verbose_name='Регистрационный номер')),
                ('short_name', models.CharField(help_text='Краткое ФИО', max_length=50, verbose_name='Краткое ФИО')),
                ('notary_district', models.CharField(blank=True, choices=[('alagir', 'Алагирский нотариальный округ'), ('ardon', 'Ардонский нотариальный округ'), ('vladik', 'Владикавказский нотариальный округ'), ('digora', 'Дигорский нотариальный округ'), ('iraf', 'Ирафский нотариальный округ'), ('kirov', 'Кировский нотариальный округ'), ('mozdok', 'Моздокский нотариальный округ г. Москвы'), ('pravober', 'Правобережный нотариальный округ'), ('prigorod', 'Пригородный нотариальный округ')], default='', help_text='Нотариальный округ', max_length=150, verbose_name='Нотариальный округ')),
                ('phone', models.CharField(blank=True, default='', help_text='Номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('mail', models.EmailField(blank=True, default='', help_text='Email', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Нотариус',
                'verbose_name_plural': 'Нотариусы',
                'ordering': ['name'],
            },
        ),
    ]
