# Generated by Django 5.2.9 on 2025-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary',
            name='fed_number',
            field=models.IntegerField(blank=True, default='', help_text='Фед. номер', verbose_name='Фед. номер'),
        ),
    ]
