# Generated by Django 5.2.9 on 2025-12-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_notary_fed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary',
            name='fed_number',
            field=models.IntegerField(blank=True, help_text='Фед. номер', null=True, verbose_name='Фед. номер'),
        ),
    ]
