# Generated by Django 5.2.9 on 2025-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_notary_fed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary',
            name='fed_number',
            field=models.CharField(blank=True, default='', help_text='Фед. номер', verbose_name='Фед. номер'),
        ),
    ]
